#!/bin/bash
COMMAND=$1
PID_LOCATION=${2:-pids}
PID_FILE=$PID_LOCATION/apache-fop-server.pid
function start {
  java -cp apache-fop-server.jar:lib/* org.zilverline.fop.FopServer &
  PID=$!
  echo $PID > $PID_FILE
  echo "Apache fop server started"
}

function stop {
  if [ -e $PID_FILE ]
  then
    kill -TERM `cat $PID_FILE`
    rm $PID_FILE
  else
    echo "Apache fop server is not running"
  fi
}

function restart {
  stop
  start
}

function status {
  if [ -e $PID_FILE ]
  then
    echo "Apache fop server is running with process id `cat $PID_FILE`"
  else
    echo "Apache fop server is not running"
  fi
}

case $COMMAND in

"start"*)
  start
  ;;
"stop"*)
  stop
  ;;
"restart"*)
  restart
  ;;
"status"*)
  status
  ;;
*)
  echo "apache-fop-server start|stop|restart|status"
  ;;
  
esac